### ISSUE TITLE
AU/Vista input voltage to OSD 

### ISSUE THREAD

**Issue by SCMicroMike** [fpv-wtf/margerine#11]
As a user of the DJI FPV without a flight controller the display of the AU/Vista input voltage would be beneficial for use with the DJI FPV system. 

The simple usecase is as follows:

- Pilot installs AU/Vista unit in an airframe with direct flight battery connection according to hardware limitations.
- Pilot powers on in AU/Vista and FPV goggles entering flight playback OSD.
- According to value read and position values the flight battery is painted to the OSD.

The following comes from @funnel on fpv.wtf Discord:
 
[](https://cdn.discordapp.com/attachments/950499167237718136/960576273665650738/unknown.png)
it's possible this is where the voltage value is in on the AU. not 100% sure, need to do more tests to confirm
`cat /sys/devices/platform/soc/f0a00000.apb/f0a71000.omc/voltage4`

[https://discordapp.com/channels/849931046883819550/950499167237718136/960576273841786910](url)

multiplied by ~0.01584

yes it is. I went through 13-16.8V with a psu and that's where you can read it. The average factor on my old big AU is  0.015833
I don't have a Vista to test

**Comment by bri3d** [comment]
https://github.com/bri3d/msp-osd/issues/1#issuecomment-1087816889

I posted some approaches here. I think building a "fake FC" functionality attached to the serial mux is plausible.

**Comment by j005u** [comment]
Closing as msp-osd supports this for a while now.
