### ISSUE TITLE
Not an issue just a question

### ISSUE THREAD

**Issue by Hrisfpv** [fpv-wtf/margerine#15]
I pulled the root files from my v2 goggles and i wanted to ask what does the debug menu do.I kinda don't want to risk my goggles just asking if anybody has tried it.

https://ibb.co/f8X5PHL
https://ibb.co/D9FFRgC

**Comment by jesuslg123** [comment]
Right now the few debug menu can be presented moving around some xml items but honestly not really much can be done right now. Don't worry about messing with XML UI files, but ALWAYS BACKUP FIRST, so in case you change something and the UI does not appear you can simply restore the original XML and UI will work again.
If a wrong XML setup is done, the UI won't boot up, but after restore to a valid version the system will work again.

**Comment by jesuslg123** [comment]
Try with [this gist](https://gist.github.com/jesuslg123/6d5e4b73457ea05b1a588edbf6c1d6e1)

Is a modified [racing_device_menu.xml](https://gist.github.com/jesuslg123/6d5e4b73457ea05b1a588edbf6c1d6e1#file-racing_device_menu-xml) which enable some debug menus.

**Comment by Hrisfpv** [comment]
so i just adb push it and reboot?

**Comment by jesuslg123** [comment]
Yes, but before that rename the original file to .original

**Comment by Hrisfpv** [comment]
Oh i got it thanks btw.Just an idea maybe you should make a discord server so that people can share hacks and ideas

**Comment by jesuslg123** [comment]
There is already a discord server, take a look on the readme of the project 😜

**Comment by j005u** [comment]
https://discord.gg/3rpnBBJKtU
