### ISSUE TITLE
problem dji googles v2  015

### ISSUE THREAD

**Issue by ellsiprod** [fpv-wtf/margerine#16]
hi i have this problem. my dji googles v2 are back from dji and they have the new firmware 015. my dji fpv holds dronehack 00 what can i do?

**Comment by a1axx** [comment]
This was raised in issue #1

**Comment by ellsiprod** [comment]
where can i see the solution?

**Comment by NiklasVoigt** [comment]
there is no solution

**Comment by j005u** [comment]
Closing as dupe of #1.
