### ISSUE TITLE
DJI goggles notification: "Firmware versions do not match"

### ISSUE THREAD

**Issue by Nimrasol** [fpv-wtf/margerine#37]
Although I updated all my Vista's and my goggles v1 to V01.00.0606 I get a DJI based pop-up notification which reports: _"Firmware versions do not match. Use DJI Assistant 2 (DJI FPV Series) to upgrade."_ at the very beginning of the transmission. The video transmission and the msp-osd  is working. If I click on _"Check"_ I can see that the goggles and the vista have the correct and equal FW version. If I click on _"Skip"_ everything is working as expected. Due my goggles and vista's are rooted I can't check the FW version anymore with DJI Assistant 2 because it reports _"Cannot load firmware list"_.

How can I get rid of this nasty pop-up when I start the transmission? Is there a way to supress it anyway?

**Comment by riddles55** [comment]
Update your dji controller. That was my issue
