### ISSUE TITLE
Air Unit Recording

### ISSUE THREAD

**Issue by Ciurrone** [fpv-wtf/margerine#38]
I fly with fixed wings and quadcopters, on fixed wings I use air units and on quadcopters I use caddx vista.
I like to record videos on the air units, but when I change from quadcopter to fixed wing, the recording on the air unit is disabled and I often forget to reactivate it from the glasses.
there would be no way that the glasses automatically switch the recording mode according to the unit used?

**Comment by stylesuxx** [comment]
No, currently there is no way of doing this.

**Comment by Ciurrone** [comment]
> No, currently there is no way of doing this.

i understand, i will try to remember to activate the recording on the air unit
Thanks for the reply
