### ISSUE TITLE
Complete dump 

### ISSUE THREAD

**Issue by druckgott** [fpv-wtf/margerine#9]
Hallo, is there already a complete dump of all files availible to take a look on the files? Maybe it's not an issues, but I do not know where I can ask this think.

**Comment by bri3d** [comment]
The filesystem content belongs to DJI so it cannot be shared. You can extract files from the firmware on your own, either from your own running hardware using adb or by using https://github.com/o-gs/dji-firmware-tools to extract DJI update files.

**Comment by druckgott** [comment]
Ah ok I understand. So I have to root it and download ist by myselve. Thx for the information.

**Comment by funneld** [comment]
You can download them from here http://dankdronedownloader.com/DDD2/app/ and extract them with the tools.
